
<%@ Register TagPrefix="cwc" Namespace="System.Web.UI.WebControls" Assembly="WebDataGrid" %>
<%@ Register TagPrefix="uc1" TagName="ModelTitle" Src="../WebControler/ModelTitle.ascx" %> 
<%@ Register Src="../WebControler/Controls/Calendar1.ascx" TagName="Calendar1" TagPrefix="uc3" %>
<%@ Control Language="C#" AutoEventWireup="true" CodeFile="wfrmM10701EnlargeSorder.ascx.cs" Inherits="Boundary_wfrmM10701EnlargeSorder" %>
<uc1:modeltitle id="ModelTitle1" runat="server"></uc1:modeltitle>
<table class="DataGridFont" cellSpacing="0" cellPadding="0" border="0" >
    <tr width="100%">
        <td width="50" rowSpan="6"><FONT face="新細明體"></FONT></td>
        <td style="width: 100px"> <asp:Label ID="lbSorder" runat="server"  ></asp:Label>
        </td>
        <td width="100"><asp:textbox id="tbSorder" runat="server"></asp:textbox></td>        
        <td width="150" align="right">
        <asp:Button ID="btnQuery" runat="server"  width="86px" OnClick="btnQuery_Click" /></td>
    </tr>     
</table>
<hr />
 <asp:datagrid id="dgSorder" runat="server" Width="50%" CssClass="DataGridFont" Font-Size="10px" EditItemStyle-HorizontalAlign="Center"  EditItemStyle-VerticalAlign="Middle" 
		BackColor="White" UserID="Any" BorderStyle="None" BorderWidth="1px" AllowPaging="false" Font-Names="Verdana"
		BorderColor="#CCCCCC" CellPadding="3"   ShowFooter="True" OnEditCommand="dgSorder_EditCommand" OnCancelCommand="dgSorder_CancelCommand" OnUpdateCommand="dgSorder_UpdateCommand" AutoGenerateColumns="False">
		<Columns> 
            <asp:BoundColumn DataField="SORDER" HeaderText="SORDER" ReadOnly="true" ItemStyle-HorizontalAlign="Center" />
            <asp:BoundColumn DataField="MODEL" HeaderText="MODEL"  ReadOnly="true" ItemStyle-HorizontalAlign="Center" />
            <asp:BoundColumn DataField="SPART" HeaderText="SPART" ReadOnly="true" ItemStyle-HorizontalAlign="Center" />
            <asp:BoundColumn DataField="PRD_TYPE" HeaderText="PRD_TYPE" ReadOnly="true"  ItemStyle-HorizontalAlign="Center" />
            <asp:BoundColumn DataField="SEQUENCE_ID" HeaderText="SEQUENCE_ID" ReadOnly="true" ItemStyle-HorizontalAlign="Center" />            
            <asp:TemplateColumn HeaderText="PID_qty" ItemStyle-HorizontalAlign="Center">
                 <ItemTemplate>
                     <asp:Label ID="Label1" Width="200" Text='<%# DataBinder.Eval(Container, "DataItem.PID_QTY")%>' runat="server"/>
                 </ItemTemplate>
                 <EditItemTemplate>
                     <asp:TextBox id="PID_QTY" Text='<%# DataBinder.Eval(Container,"DataItem.PID_QTY") %>' runat="server" Width="100%"/>
                 </EditItemTemplate>
             </asp:TemplateColumn>
             <asp:EditCommandColumn HeaderText="EDIT"  ButtonType="LinkButton"  CancelText="Cancel" EditText="Edit" UpdateText="Update"  ItemStyle-ForeColor="red" />
        </Columns>
	<SelectedItemStyle Font-Bold="True" ForeColor="White" BackColor="#669999"></SelectedItemStyle>
		<AlternatingItemStyle BackColor="WhiteSmoke"></AlternatingItemStyle>
		<EditItemStyle BackColor="White" />
		<ItemStyle ForeColor="#000066" BackColor="Cornsilk"></ItemStyle>
		<HeaderStyle Font-Bold="True" HorizontalAlign="Center" ForeColor="White"
			BackColor="SteelBlue"></HeaderStyle>
		<FooterStyle ForeColor="#000066" BackColor="White"></FooterStyle>
		<PagerStyle HorizontalAlign="Left" Mode="NumericPages"></PagerStyle>
</asp:datagrid>
<%-- <asp:GridView ID="gvSorder" runat="server" CssClass ="DataGridFont" AutoGenerateColumns="False" AllowPaging="True" PageSize="10" AutoGenerateSelectButton="True" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
            <Columns>
                <asp:BoundField DataField="SORDER" HeaderText="SORDER" />
                <asp:BoundField DataField="MODEL" HeaderText="MODEL" />
                <asp:BoundField DataField="SPART" HeaderText="SPART" />
                <asp:BoundField DataField="PRD_TYPE" HeaderText="PRD_TYPE" />
                <asp:BoundField DataField="SEQUENCE_ID" HeaderText="SEQUENCE_ID" />
                <asp:BoundField DataField="PID_QTY" HeaderText="PID_QTY" />
                <asp:BoundField DataField="INPUT_QTY" HeaderText="INPUT_QTY" />
            </Columns>
            <SelectedRowStyle BorderColor="#669999" />
            <AlternatingRowStyle BackColor="WhiteSmoke" />
            <FooterStyle BackColor="#000066" />
            <HeaderStyle BackColor="#006699" />
            <RowStyle Wrap="False" />
        </asp:GridView>--%>
        
        <%--
        <asp:DataGrid id="People" runat="server" BorderColor="green" Width="640" PageSize="5" AllowPaging="true" OnPageIndexChanged="Page_Grid" BorderWidth="1" CellPadding="3"
             AutoGenerateColumns="false" ShowHeader="true" Visible="true" OnEditCommand="People_Edit" OnCancelCommand="People_Cancel" 
             OnUpdateCommand="People_Update" OnDeleteCommand="People_Delete">
             <HeaderStyle BorderColor="White" BackColor="black" ForeColor="White" Font-Bold="True" Font-Name="Arial" Font-Size="9" HorizontalAlign="Center"/>
             <ItemStyle   BorderColor="" BackColor="#FFFFF0" ForeColor="Black" Font-Name="Arial" Font-Size="8" Font-Bold="False" HorizontalAlign="Center"/>
             <EditItemStyle   BorderColor="" BackColor="#FFFFF0" ForeColor="Black" Font-Name="Arial" Font-Size="7" Font-Bold="False" HorizontalAlign="Center"/>
             <PagerStyle Mode="NumericPages" Font-Size="8"/>
             <Columns>
                 <asp:BoundColumn HeaderText="ID" ReadOnly="true" DataField="pkID"/>
                 <asp:TemplateColumn>
                     <HeaderTemplate>
                         <b> First Name </b>
                     </HeaderTemplate>
                     <ItemTemplate>
                         <asp:Label ID="Label1" Text='<%# DataBinder.Eval(Container.DataItem, "FirstName").ToString().Trim() %>' runat="server"/>
                     </ItemTemplate>
                     <EditItemTemplate>
                         <asp:TextBox id="FirstName" Text='<%# DataBinder.Eval(Container.DataItem, "FirstName").ToString().Trim() %>' runat="server" Width="100%"/>
                     </EditItemTemplate>
                 </asp:TemplateColumn>
                 <asp:TemplateColumn>
                     <HeaderTemplate>
                         <b> Last Name </b>
                     </HeaderTemplate>
                     <ItemTemplate>
                         <asp:Label ID="Label2" Width="200" Text='<%# DataBinder.Eval(Container.DataItem, "LastName").ToString().Trim() %>' runat="server"/>
                     </ItemTemplate>
                     <EditItemTemplate>
                         <asp:TextBox id="LastName" Text='<br><%# DataBinder.Eval(Container.DataItem, "LastName").ToString().Trim() %>' runat="server" Width="100%"/>
                     </EditItemTemplate>
                 </asp:TemplateColumn>
                 <asp:EditCommandColumn ButtonType="LinkButton" CancelText="Cancel" EditText="Edit" UpdateText="Update" />
                 <asp:ButtonColumn Text= "Delete" CommandName="Delete"></asp:ButtonColumn> 
             </Columns>
         </asp:DataGrid>--%>
