<%@ Control Language="C#" AutoEventWireup="true" CodeFile="WFrmModuleManage.ascx.cs" Inherits="Boundary_WFrmModuleManage" %>

<table width="100%" height="100%" border="1">
  <tr>
    <td valign="top" style="height: 20px">&nbsp;
      <asp:Label ID="LblFTabID" runat="server" Text="Label"></asp:Label>
        <asp:TextBox ID="TbFTabID" runat="server"></asp:TextBox>
    <asp:Button ID="BtnQuery" runat="server" Text="Query" OnClick="BtnQuery_Click" /></td>
  </tr>
  <tr>
    <td valign="top"><asp:DetailsView ID="DetailFunction" runat="server" Height="50px" Width="487px" AutoGenerateRows="False" OnItemDeleting="DetailFunction_ItemDeleting" OnItemInserting="DetailFunction_ItemInserting" OnItemUpdating="DetailFunction_ItemUpdating" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" OnItemCommand="DetailFunction_ItemCommand" CssClass="FontDataGrid">
        <Fields>
            <asp:BoundField DataField="ftabid" HeaderText="FTabID" />
            <asp:BoundField DataField="fdesktopsrc" HeaderText="FDeskTopSrc" />
            <asp:BoundField DataField="Description" HeaderText="Description" />
            <asp:BoundField DataField="FPARENTID" HeaderText="FPARENTID" />
            <asp:BoundField DataField="FTABORDER" HeaderText="FTABORDER" />
        </Fields>
        </asp:DetailsView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server"></asp:SqlDataSource>
        <asp:GridView ID="GridFunction" runat="server" AutoGenerateColumns="False" AutoGenerateSelectButton="True" OnSelectedIndexChanging="GridFunction_SelectedIndexChanging" AllowPaging="True" PageSize="25" DataKeyNames="DataGridFont" CssClass="FontDataGrid">
            <Columns>
                <asp:BoundField DataField="ftabid" HeaderText="FTabID" />
                <asp:BoundField DataField="FDESKTOPSRC" HeaderText="FDeskTopSrc" />
                <asp:BoundField DataField="DESCRIPTION" HeaderText="Description" />
                <asp:BoundField DataField="FPARENTID" HeaderText="FPARENTID" />
                <asp:BoundField DataField="FTABORDER" HeaderText="FTABORDER" />
            </Columns>
            <RowStyle Wrap="False" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
    </td>
  </tr>
</table>
